format = """
$hostname\
$directory\
[](fg:red bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:green bg:cyan)\
$docker_context\
$direnv\
$nix_shell\
$os\
[](fg:cyan bg:blue)\
[ 󰩗 ](bg:blue)\
[](fg:blue)\
$line_break\
$username\
$character\
"""

right_format = "$cmd_duration"

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "purple"
style_root = "red bold"
format = '[]($style)[$user ](bg:$style)[]($style)'
disabled = false

[character]
format = "[](inverted purple)[](purple) "

[hostname]
ssh_only = true
ssh_symbol = "󰌘 "
style = "green"
format = "[]($style)[$ssh_symbol$hostname ](bg:$style)[](inverted $style)"

[directory]
style = "red"
format = "[]($style)[$path ](bg:$style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Applications" = "󱧺 "
"Desktop" = "󱂵 "
"Documents" = "󱧶 "
"Downloads" = "󰉍 "
"Music" = "󱍙 "
"Pictures" = "󰉏 "
"Public" = "󱞊 "
"Github" = " "
"Code" = "󰨞 "
"Docker" = " "
".config" = ".󱁿 "
".ssh" = ".󱊪 "
"fish" = "󰈺 "
"kitty" = "󰄛 "
"neofetch" = "󱡠 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[git_branch]
symbol = ""
style = "bg:yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow"
format = '[$all_status$ahead_behind ]($style)'


[direnv]
disabled = false
format = "[ $loaded$allowed](bg:$style)"
style = "cyan"
unloaded_msg = "󱧊 "
loaded_msg = "󱥾 "
allowed_msg = ""
not_allowed_msg = "󰀦 "
denied_msg = "󰅖 "

[nix_shell]
format = "[$symbol$state$name ](bg:$style)"
symbol = " "
style = "cyan"
pure_msg = " "
impure_msg = ""

[os]
disabled = true
style = "cyan"
format = "[ $symbol$name ](bg:$style)"

[os.symbols]
Mint = "󰣭 "


[docker_context]
symbol = " "
only_with_files = false
style = "bg:cyan"
format = '[ $symbol $context ]($style) $path'


[c]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "󱘗"
style = "bg:green"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:green"
format = '[ $symbol ($version) ]($style)'


[cmd_duration]
format = "[]($style)[ 󱎫 $duration ](bg:$style)[](inverted $style)"
style = "blue bold"
min_time = 1_000
show_notifications = false
min_time_to_notify = 30_000

[time]
disabled = false
time_format = "%R"                                                       # Hour:Minute Format
style = "blue"
format = '[](bg:red fg:$style)[ $time ](bg:$style)[](inverted $style)'
