format = """
$hostname\
$directory\
[](fg:maroon bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:teal)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:teal bg:sapphire)\
$docker_context\
$nix_shell\
$os\
[](fg:sapphire bg:lavender)\
[ 󰩗 ](bg:lavender)\
[](fg:lavender)\
$line_break\
$username\
$character\
"""

right_format = "$cmd_duration"

palette = 'catppuccin_latte'
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:mauve fg:#1e1e2e"
style_root = "bold bg:red fg:#1e1e2e"
format = '[](inverted $style)[$user ]($style fg:base)[](inverted $style)'
disabled = false

[character]
format = "[](bg:mauve fg:#1e1e2e)[](fg:mauve bg:#1e1e2e) "

[hostname]
ssh_only = true
ssh_symbol = "󰌘 "
style = "green"
format = "[](fg:$style)[$ssh_symbol$hostname ](fg:base bg:$style)[](inverted $style)(fg:text)"

[directory]
style = "maroon"
format = "[](fg:$style)[$path ](bg:$style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Applications" = "󱧺 "
"Desktop" = "󱂵 "
"Documents" = "󱧶 "
"Downloads" = "󰉍 "
"Music" = "󱍙 "
"Pictures" = "󰉏 "
"Public" = "󱞊 "
"Github" = " "
"Code" = "󰨞 "
"Docker" = " "
".config" = ".󱁿 "
".ssh" = ".󱊪 "
"fish" = "󰈺 "
"kitty" = "󰄛 "
"neofetch" = "󱡠 "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[nix_shell]
format = "[ $symbol$state$name ]($style)"
symbol = " "
style = "bg:sapphire"
pure_msg = " "
impure_msg = ""

[os]
disabled = true # Disabled by default
style = "bg:sapphire"
format = "[ $symbol$name ]($style)"

[os.symbols]
Mint = "󰣭 "

[cmd_duration]
format = "[]($style)[ 󱎫 $duration ](fg:base bg:$style)[](inverted $style)"
style = "peach bold"
min_time = 1_000
show_notifications = true
min_time_to_notify = 30_000

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:lavender"
format = '[$time ]($style)'


[c]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
only_with_files = false
style = "bg:sapphire"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:teal"
format = '[ $symbol ($version) ]($style)'


[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
